media:
  input: public/assets/img
  output: /assets/img
content:
  - name: home_page
    label: Startseite
    path: content/home/content.json
    type: file
    fields:
      - name: carousel
        label: Karusell
        list: true
        type: object
        fields:
          - name: title1
            label: Titel1
            type: string
          - name: title2
            label: Titel2
            type: string
          - name: text
            label: Text
            type: string
          - name: background_image
            label: Hintergrundbild
            type: image

      - name: textwithcta
        label: Willkommenstext
        type: object
        fields:
          - name: title
            label: Titel
            type: string
          - name: text
            label: Text
            type: text

      - name: serviceoverview
        label: Serviceübersicht
        type: object
        fields:
          - name: title
            label: Titel
            type: string
          - name: services
            label: Dienstleistungen
            type: object
            list: true
            fields:
              - name: icon
                label: Symbol
                type: string
              - name: title
                label: Titel
                type: string
              - name: description
                label: Beschreibung
                type: text

      - name: textimageleft
        label: Text mit Bild (L)
        type: object
        fields:
          - name: title
            label: Titel
            type: string
          - name: text
            label: Text
            type: text
          - name: image
            label: Bild
            type: image
          - name: imagealt
            label: Bildbeschreibung
            type: string

  - name: aboutus_page
    label: Über uns Seite
    path: content/aboutus/content.json
    type: file
    fields:
      - name: intro
        label: Einleitungstext mit Bild
        type: object
        fields:
          - name: title
            label: Titel
            type: string
          - name: subtitle
            label: Untertitel
            type: text
          - name: images
            label: Bilder
            type: object
            list: true
            fields:
              - name: image
                label: Bild
                type: image
              - name: imagealt
                label: Bildbeschreibung
                type: string
      - name: mission
        label: Unsere Mission
        type: object
        fields:
          - name: title
            label: Titel
            type: string
          - name: text
            label: Text
            type: rich-text
      - name: breakImage
        label: Trennbild
        type: image
        
      - name: gruende
        label: Gründe für unser Unternehmen
        type: object
        fields:
          - name: title
            label: Titel
            type: string
          - name: subtitle
            label: Untertitel
            type: string
          - name: gruende
            label: Gründe
            type: object
            list: true
            fields:
              - name: title
                label: Titel
                type: string
              - name: description
                label: Beschreibung
                type: text

      - name: kooperationen
        label: Kooperationspartner
        type: object
        fields:
          - name: title
            label: Titel
            type: string
          - name: subtitle
            label: Untertitel
            type: string
          - name: partner
            label: Partner
            type: object
            list: true
            fields:
              - name: partnername
                label: Partnername
                type: string
              - name: description
                label: Beschreibung
                type: text
              - name: partnerimage
                label: Partnerlogo
                type: image
            
      - name: team
        label: Team
        type: object
        fields:
          - name: title
            label: Titel
            type: string
          - name: subtitle
            label: Untertitel
            type: string
          - name: persons
            label: Personen
            type: object
            list: true
            fields:
              - name: name
                label: Name
                type: string
              - name: position
                label: Position
                type: string
              - name: image
                label: Bild
                type: image
  - name: services
    label: Leistungen
    path: content/services/content.json
    type: file
    fields:
      - name: title
        label: Titel
        type: string
      - name: subtitle
        label: Untertitel
        type: string
      - name: services
        label: Leistungen
        type: object
        list: true
        fields:
          - name: name
            label: Name
            type: string
          - name: title
            label: Titel
            type: string
          - name: subtitle
            label: Untertitel
            type: string
          - name: description
            label: Beschreibung
            type: text
          - name: image
            label: Bild
            type: image
          - name: imagealt
            label: Bildbeschreibung
            type: string
          - name: subservice
            label: Unterleistungen
            type: object
            list: true
            fields:
              - name: title
                label: Titel
                type: string
