media:
  input: public/assets/img
  output: ./assets/img
content:
  - name: home_page
    label: Home Page
    path: content/home/content.json
    type: file
    fields:
      - name: banner
        label: Banner
        type: object
        fields:
          - name: title1
            label: Title1
            type: string
          - name: title2
            label: Title2
            type: string
          - name: text
            label: Text
            type: string
          - name: background_image
            label: Background Image
            type: image

      - name: textimageright
        label: Text with Image (R)
        type: object
        fields:
          - name: title
            label: Title
            type: string
          - name: text
            label: Text
            type: text
          - name: image
            label: Image
            type: image
          - name: imagealt
            label: Image Alt
            type: string

      - name: serviceoverview
        label: Service Overview
        type: object
        fields:
          - name: title
            label: Title
            type: string
          - name: subtitle
            label: Subtitle
            type: string
          - name: services
            label: Services
            type: object
            list: true
            fields:
              - name: icon
                label: Icon
                type: string
              - name: title
                label: Title
                type: string
              - name: description
                label: Description
                type: text

      - name: textimageleft
        label: Text with Image (L)
        type: object
        fields:
          - name: title
            label: Title
            type: string
          - name: text
            label: Text
            type: text
          - name: image
            label: Image
            type: image
          - name: imagealt
            label: Image Alt
            type: string

      - name: cta
        label: CTA Section
        type: object
        fields:
          - name: title
            label: Title
            type: string
          - name: subtitle
            label: Subtitle
            type: string
          - name: image
            label: Image
            type: image
          - name: cta_button_left
            label: CTA Button Left
            type: object
            fields:
              - name: path
                label: Path
                type: string
              - name: label
                label: Label
                type: string
          - name: cta_button_right
            label: CTA Button Right
            type: object
            fields:
              - name: path
                label: Path
                type: string
              - name: label
                label: Label
                type: string
