media:
  input: assets/img
  output: img
content:
  - name: home_page
    label: Home Page
    path: content/home/content.json
    type: file
    fields:
      - name: header
        label: Header
        type: object
        fields:
          - name: logo
            label: Logo
            type: image
  
      - name: banner
        label: Banner
        type: object
        fields:
          - name: heading
            label: Heading
            type: string
          - name: text
            label: Text
            type: string

      - name: textimageright
        label: Text with Image (R)
        type: object
        fields:
          - name: title
            label: Title
            type: string
          - name: text
            label: Text
            type: string
          - name: image
            label: Image
            type: image

      - name: serviceoverview
        label: Service Overview
        type: object
        fields:
          - name: title
            label: Title
            type: string
          - name: subtitle
            label: Subtitle
            type: string
          - name: services
            label: Services
            type: object
            list: true
            fields:
              - name: icon
                label: Icon
                type: image
              - name: title
                label: Title
                type: string
              - name: subtitle
                label: Subtitle
                type: string

      - name: textimageleft
        label: Text with Image (L)
        type: object
        fields:
          - name: title
            label: Title
            type: string
          - name: text
            label: Text
            type: string
          - name: image
            label: Image
            type: image

      - name: cta
        label: CTA Section
        type: object
        fields:
          - name: title
            label: Title
            type: string
          - name: subtitle
            label: Subtitle
            type: string
          - name: image
            label: Image
            type: image
          - name: cta_button_left
            label: CTA Button Left
            type: object
            fields:
              - name: path
                label: Path
                type: string
              - name: label
                label: Label
                type: string
          - name: cta_button_right
            label: CTA Button Right
            type: object
            fields:
              - name: path
                label: Path
                type: string
              - name: label
                label: Label
                type: string
