media:
  input: assets/img
  output: img
content:
  - name: landing_page
    label: Landing Page
    path: content
    type: collection
    view:
      fields: [ title, subtitle]
    fields:
      - name: title
        label: Title
        type: string
      - name: subtitle
        label: subtitle
        type: rich-text
  - name: landing_page_file
    label: Landing Page File
    path: content/landingPage/content.json
    type: file
    fields:
      - name: title
        label: Title
        type: string