name: Deploy to server

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types:
      - closed
      
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H home145705756.1and1-data.host >> ~/.ssh/known_hosts

    - name: Copy files to server
      run: |
        scp -r ./dist/* u39282224@home145705756.1and1-data.host:/path/to/your/app

    - name: Run build
      run: |
        npm i
        npm run build
        
