name: Deploy to server

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types:
      - closed
      
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H home145705756.1and1-data.host >> ~/.ssh/known_hosts

  # - name: Copy files to server
  #  run: |
  #    scp -r ./dist/* u39282224@home145705756.1and1-data.host:/GIM-Prod
    - name: Copy files to server
      run: |
        echo "mkdir -p /GIM-Prod" > sftp_batch
        echo "put -r ./dist/* /GIM-Prod/" >> sftp_batch
        
        sftp -b sftp_batch u39282224@home145705756.1and1-data.host

    - name: Run build
      run: |
        npm i
        npm run build
        
