name: Rebuild and Deploy Website

on:
  push:
    branches:
      - main  # Replace with your default branch if different
    paths:
      - 'content/**'  # Adjust to the path where your CMS updates content

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'  # Use the version required by your project

    - name: Install Dependencies
      run: npm install

    - name: Generate Static Files
      run: npm run generate

    - name: Sync Generated Files to Docs Folder
      run: |
        rsync -av --delete dist/ docs/ --exclude=".nojekyll" --exclude="CNAME"

    - name: Commit and Push Changes
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add docs/
        git commit -m "Update static site content"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
